# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8415ef9cbebdc330ec00c12c4abc07b16698907e942d9c33a30be27390188e8fc8d9a393045cb64cd1d4ed90187d43fb2ee05cc149a7ca950fa0c3d6be363b37

test:
  secret_key_base: b8dd1eefe821bd41ac56767d739d681ae9bbfbc7e36d46cdf91caf5c009181f2389141d1f3e07fe63023472bfbdfb5bc8eeceed5902165fa0722f7df4c1dd2a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
